#!/bin/bash
# Retrieve arguments
domain=$1
path=$2
admin_movim=$3
language=$4
is_public=$5

# Check if admin exists
sudo yunohost user list --json | grep -q "\"username\": \"$admin_movim\""
if [[ ! $? -eq 0 ]]; then
	echo "Wrong admin"
	exit 1
fi
sudo yunohost app setting movim admin -v $admin_wordpress
sudo yunohost app setting movim language -v $language
sudo yunohost app setting movim is_public -v $is_public

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a movim
if [[ ! $? -eq 0 ]]; then
	exit 1
fi

# Generate random password
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')

# Use 'movim' as database name and user
db_user=movim

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd
sudo yunohost app setting movim mysqlpwd -v $db_pwd

# Copy files to the right place
final_path=/var/www/movim
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path

# Set permissions to movim directory
sudo chown -R www-data: $final_path

# Call Mud to create table
sudo php mud.php db set

# Update admin configuration
sudo php mud.php config blabla
